#!/usr/bin/env perl

# Pragmas.
use strict;
use warnings;

# Modules.
use PYX::Parser;

# Open file.
my $file_handler = *STDIN;
if ($ARGV[0]) {
	if (! open(INF, "<$ARGV[0]")) {
		die "Cannot open file '$ARGV[0]'.";
	}
	$file_handler = *INF;
}

# PYX::Parser object.
my $parser = PYX::Parser->new(
	'input_file_handler' => $file_handler,
	'start_tag' => \&start_tag,
	'end_tag' => \&end_tag,
);
$parser->parse;

# Close file.
if ($ARGV[0]) {
	close(INF);
}

#------------------------------------------------------------------------------
sub start_tag {
#------------------------------------------------------------------------------
# Start tag handler.

	my $tag = shift;
	print "Start of tag '$tag'.\n";
}

#------------------------------------------------------------------------------
sub end_tag {
#------------------------------------------------------------------------------
# End tag handler.

	my $tag = shift;
	print "End of tag '$tag'.\n";
}
