#!/usr/bin/env perl

# Pragmas.
use strict;
use warnings;

# Modules.
use PYX::Checker;

# Open file.
my $file_handler = *STDIN;
my $file = $ARGV[0];
if ($file) {
	if (! open(INF, '<', $file)) {
		die "Cannot open file '$file'.";
	}
	$file_handler = *INF;
}

# PYX::Checker object.
my $checker = PYX::Checker->new(
	'debug' => 1,
);

# For every lines.
while (my $line = <$file_handler>) {
	chomp $line;
	$checker->data($line);
}

# Close file.
if ($file) {
	close(INF);
}
